# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            chhavip
tagline:          'Developer, Coder, Teacher, Student and everything in between'
description:      'Developer, Coder, Teacher, Student and everything in between Explore <a href="https://twitter.com/chhavip04" target="_blank">@chhavip04</a>.'
url:              http://chhavip.github.io/
baseurl:          http://chhavip.github.io/

author:
  name:           'Chhavi P. GUpta'
  url:            https://twitter.com/chhavip04

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/chhavip
